In [19]:
import numpy as np
P = np.matrix([[8/10, 1/10, 1/10, 0],[1/10, 5/10, 2/10, 2/10],
    [1/10, 3/10, 3/10, 3/10], [0, 0, 0, 1]])
P

matrix([[0.8, 0.1, 0.1, 0. ],
        [0.1, 0.5, 0.2, 0.2],
        [0.1, 0.3, 0.3, 0.3],
        [0. , 0. , 0. , 1. ]])

In [18]:
from numpy import linalg as LA
p2 = LA.matrix_power(P,2)
p2

matrix([[0.66, 0.16, 0.13, 0.05],
        [0.15, 0.32, 0.17, 0.36],
        [0.14, 0.25, 0.16, 0.45],
        [0.  , 0.  , 0.  , 1.  ]])

In [14]:
from scipy.linalg import fractional_matrix_power
pmonthly = fractional_matrix_power(P, 1/12)
pmonthly

array([[ 0.98018689,  0.00883435,  0.01417896, -0.00320021],
       [ 0.01061589,  0.92874231,  0.04439177,  0.01625004],
       [ 0.01239743,  0.06747842,  0.88256901,  0.03755515],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])